Victor:
  Dataset: "C:\\home_screen\\programming\\algoritm and data structure\\Dataset"
  SIFT: "CustomDescriptors\\SiftDescriptor\\main.exe"
  Test: "C:\\home_screen\\programming\\algoritm and data structure\\ArtForgeryDetection\\src\\dataset\\test"
