Victor:
  Dataset: "C:\\home_screen\\programming\\algoritm and data structure\\Dataset"
  SIFT: "CustomDescriptors\\SiftDescriptor\\main.exe"
  FACE: "CustomDescriptors\\FaceDescriptor\\shape_predictor_68_face_landmarks.dat"
  Test: "dataset\\test"
