Victor:
  Dataset: "C:\\home_screen\\programming\\algoritm and data structure\\Dataset"
  SIFT: "CustomDescriptors\\SiftDescriptor\\main.exe"
  Test: [
        "dataset\\test\\artist\\mona_original.png",
        "dataset\\test\\other_artist\\mona_younger_1.jpg",
        "dataset\\test\\other_artist\\mona_younger_2.jpg",
        "dataset\\test\\other_artist\\mona_younger_3.jpg",
        "dataset\\test\\other_artist\\mona_younger_4.jpg"
        ]
